### ISSUE TITLE
Question: Dijkstra Algorithm

### ISSUE THREAD

**Issue by Lazypersonfive** [CircuitMurderer/path_finder#1]
Hi！ Thanks for your impressive codes. Could u explain the reason of Dijkstra algorithm? I mean, How It Works?

**Comment by CircuitMurderer** [comment]
Certainly! Dijkstra's algorithm is a popular method used to find the shortest path between nodes in a graph, particularly in situations where all edge weights are non-negative. It's named after its inventor, Dutch computer scientist Edsger W. Dijkstra.

The primary goal of Dijkstra's algorithm is to find the shortest path from a starting node to all other nodes in the graph. It operates by iteratively exploring the nodes and updating their minimum distances from the source node as it progresses.

Here's a step-by-step explanation of how Dijkstra's algorithm works:

1. **Initialization:**
   - Start with a graph representation, including nodes and edges.
   - Assign a tentative distance value to every node in the graph. Set the distance of the starting node to 0 and all other nodes' distances to infinity.
   - Create an empty set to keep track of visited nodes.

2. **Algorithm Iteration:**
   - While there are unvisited nodes:
     - Choose the node with the smallest tentative distance from the set of unvisited nodes.
     - Mark this node as visited.
     - For the current node, examine all of its neighboring nodes and calculate their tentative distances through the current node. Update their tentative distances if a shorter path is found.
     - For each neighboring node:
       - Calculate the total distance from the starting node to the neighboring node through the current node.
       - If this total distance is shorter than the previously recorded distance, update the distance.
   
3. **Termination:**
   - Once all nodes have been visited or if the smallest tentative distance among the unvisited nodes is infinity (indicating there is no path), the algorithm terminates.
   - The shortest path tree or shortest path distances from the source node to all other nodes in the graph have been determined.

4. **Path Reconstruction (optional):**
   - To find the shortest path from the source node to a specific destination node, trace back through the recorded shortest distances and the path taken.

Dijkstra's algorithm guarantees the shortest path in graphs where all edge weights are non-negative. However, it does not work well with graphs containing negative edge weights or cycles with negative total weight, as this can lead to incorrect results.

The algorithm's time complexity can be optimized using various data structures such as priority queues or heaps, resulting in an efficient runtime, typically O((V + E) log V), where V is the number of vertices and E is the number of edges in the graph.

Overall, Dijkstra's algorithm is widely used in various applications, including network routing protocols, GPS systems, and transportation networks, due to its ability to efficiently find the shortest path in a graph.
